### ISSUE TITLE
Question about decompiled code

### ISSUE THREAD

**Issue by vlad-ivanov-name** [ernacktob/esp8266_wifi_raw#2]
Hello,

this isn't really an issue, but I haven't found any way to contact @ernacktob . Could you please tell whether you do decompiling by hand or use some tools? If so, what kind of decompliler supports xtensa? Thanks.

**Comment by ernacktob** [comment]
Hello @resetnow, sorry for the late reply I don't follow this repo much anymore :/

I did the decompiling by hand as much as I could, which, as you can probably imagine, was pretty tedious and error-prone... I did not find automated decompilers for xtensa, but it would be neat if someone made one.

I probably won't be working on that much more, but feel free to use whatever I have here as help for your own projects. Hopefully this was useful to someone :) Hasn't Espressif come up with some new SDK already, though?

**Comment by vlad-ivanov-name** [comment]
That's an impressive amount of code done by hand, seriously. There is racedo-lib in radare2, but it's under development and can't be used out of the box.

> Hasn't Espressif come up with some new SDK already, though?

They sort of did, but it's for ESP32 and it still relies on binary libs for phy, mac, rtc and other stuff.

Thanks for the reply!
